apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
        - name: postgress
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER 
              value: postgress
            - name: POSTGRES_PASSWORD
              value: postgress
    