apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
  labels:
    env: rc-testing
spec:
  replicas: 5
  template:
    metadata:
      name: pod-name
      labels:
        env: rc-pod
    spec:
      containers:
        - name: rc-container
          image: nginx:latest