apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: db-tier
spec:
  containers:
    - name: postgres
      image: postgres
      env:
      - name: POSTGRES_PASSWORD
        value: mysecretpassword
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  initContainers:
    - name: init-containe-name
      image: busybox
      command: ['sh', '-c', 'echo "Init container running..."; sleep 5']
        
