apiVersion: v1
kind: Pod
metadata:
  name: nitin1
spec:
  containers:
    - name: nitin-container
      image: nginx
      ports:
        - containerPort: 80
  tolerations:
    - key: "mysize"         # if effect is not given then it will be able to 
      operator: "Equal"     #by default it is Equal.
      value: "large"
      effect: "NoSchedule"  # if effect is not given then it will be able to tolerate all taints.
      