apiVersion: v1
kind: Pod
metadata:
  name: pod-name3
  labels:
    app: v1
    env: test
spec:
  containers:
    - name: test
      image: coolgourav147/nginx-custom

      envFrom:
        - configMapRef:      # cm2.KEY : cm2.VALUE
              name: cm2



      env:
        - name: variable-from-cm2
          valueFrom:
            configMapKeyRef:                  # variable-from-cm2 : cm2.database.properties.VALUE
              key: database.properties
              name: cm2