apiVersion: v1
kind: Pod
metadata:
  name: pod-name3
  labels:
    app: v1
    env: test
spec:
  containers:
    - name: test
      image: coolgourav147/nginx-custom

      envFrom:
        - secretRef:
              name: secret-name   #secret-name.KEY : secret-name3.VALUE



      env:
        - name: secret-variable-name
          valueFrom:
            secretKeyRef:
              key: application.properties    #secret-variable-name : secret-name3.application.properties.VALUE
              name: secret-name3