apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  labels:
    app: v1
    env: test
  namespace: my-namespace
spec:
  containers:
    - name: test
      image: coolgourav147/nginx-custom
      resources:
        requests:
          memory: 100Mi
          cpu: 0.1
        limits:
          memory: 200Mi
          cpu: 0.3