apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  labels:
    tag: hemlo
spec:
  hard:
    pods: 5
    requests.cpu: 0.5
    requests.memory: 500Mi
    limits.cpu: 1
    limits.memory: 1Gi


    