apiVersion: v1
kind: Pod 
metadata:
  name: pod-name
  labels:
    name: about-label
    description: spec-act-as-a-tag 
spec:
  containers:
  - name: name-of-container
    image: nginx
    ports:
      - containerPort: 80
  - name: not-recommended-to-run-more-than-one-container-in-single-pod
    image: busybox
    command: ["sleep", "3600"]
    ports:
      - containerPort: 3000 